### ISSUE TITLE
파일 시간 받아오는 코드 조사

### ISSUE THREAD

**Issue by ChoiJuEon** [junegives/Assignment2#11]
time_t값을 활용할 수 있게 가공시켜주는 함수인 localtime() 함수를 조사합니다.

**Comment by ChoiJuEon** [comment]
struct tm *localtime(const time_t* timep); 으로 파일의 정보를 timer가 가리키는 변수를 지역 시간 기준으로 구조체로 변환해 그 주소를 반환한다. 이때 const time_t*timep는 time_t형 변수를 가리키는 포인터이다.
struct tm*localtime의 구조체는 다음과 같이 구성되어 있습니다.
struct tm {
int tm_sec; /* seconds */
int tm_min; /* minutes */
int tm_hour; /* hours */
int tm_mday; /* day of the month */
int tm_mon; /* month */
int tm_year; /* year */
int tm_wday; /* day of the week */
int tm_yday; /* day in the year */
int tm_isdst; /* daylight saving time */
};

이떄 month의 경우 0부터 시작합니다.(1월이 0월로 나타남)

**Comment by junegives** [comment]
그렇다면 month의 경우 +1을 해주어야 하겠군요!!
잘 알겠습니다~~
