### ISSUE TITLE
git pull 직후 아래와 같은 에러가 발생하였습니다

### ISSUE THREAD

**Issue by tkdgh1013** [junegives/Assignment2#13]
E325: ATTENTION
Found a swap file by the name ".main.c.swp"
          owned by: sangho   dated: Thu Apr 26 01:30:10 2018
         file name: ~sangho/Assignment2/main.c
          modified: no
         user name: sangho   host name: ubuntu
        process ID: 36490 (still running)
While opening file "main.c"
             dated: Thu Apr 26 01:41:18 2018
      NEWER than swap file!

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r main.c"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file ".main.c.swp"
    to avoid this message.

**Comment by ChoiJuEon** [comment]
https://extrememanual.net/6469
비슷한 문제 해결법

**Comment by duswl9801** [comment]
git stash 치고 pull하시면 됩니다.
