### ISSUE TITLE
Wiki 작성

### ISSUE THREAD

**Issue by junegives** [junegives/Assignment2#15]

**Comment by ChoiJuEon** [comment]
https://typora.io/
위키 자동 변환 문서입니다.

**Comment by ChoiJuEon** [comment]
https://gist.github.com/taeukme/51287a369a84c393a6c8c00df9e6085a
READ.me 템블릿입니다.

**Comment by ChoiJuEon** [comment]
현재 결과값
<img width="515" alt="kakaotalk_20180426_204533735" src="https://user-images.githubusercontent.com/37688335/39304678-65a28d74-4995-11e8-89c0-126f80d3b255.png">

**Comment by ChoiJuEon** [comment]
text2를 바꾼 결과값
<img width="519" alt="kakaotalk_20180426_205110847" src="https://user-images.githubusercontent.com/37688335/39304732-a0c6bc18-4995-11e8-97cd-0c639672e995.png">

**Comment by duswl9801** [comment]
wiki에서 stat()함수,  실행화면, 텍스트 바뀐내용 쓰겠습니다.

**Comment by ChoiJuEon** [comment]
확인했습니다.

**Comment by junegives** [comment]
역할분담 작성하였습니다.

**Comment by junegives** [comment]
모두들 수고하셨습니다!

**Comment by duswl9801** [comment]
시간 같을때
![kakaotalk_20180427_062154651](https://user-images.githubusercontent.com/37291010/39332844-3ae788de-4998-11e8-8d16-f18a5b1ad3f0.png)

**Comment by duswl9801** [comment]
시간 다를때
![kakaotalk_20180427_062200914](https://user-images.githubusercontent.com/37291010/39332911-7e0dd118-4998-11e8-91d5-921b9f12069a.png)
