### ISSUE TITLE
파일 수정 시간 (월/일) 비교 코드 작성

### ISSUE THREAD

**Issue by ChoiJuEon** [junegives/Assignment2#3]

**Comment by ChoiJuEon** [comment]
다른 반복문이나 효율적인 함수를 알려주세요!
//두 개의 파일 수정 날짜를 비교하는 함수 작성
void datecmp(void)
{
	if (time1->tm_mon+1 > time2->tm_mon+1)
		printf("text2 is early");
	else if (time1->tm_mon+1 < time2->tm_mon+1)
                printf("text1 is early");
	else if (time1->tm_mday = time2->tm_mday)
                if(time1->tm_mday > time2_>tm_mday)
			printf("text2 is early");
		else  if(time1->tm_mday > time2_>tm_mday)
                        printf("text1 is early");
		else  if(time1->tm_mday < time2_>tm_mday)
                        printf("same text");
}

**Comment by junegives** [comment]
깔끔하게 잘 작성하셨네요

**Comment by ChoiJuEon** [comment]
if else 문의 변경 있습니다.
//파일 수정 날짜를 비교하는 함수
void datecmp(void)
{
	printf("date: ");
	if (time1.tm_mon+1 > time2.tm_mon+1)
                printf("text2 is early\n");
        else if (time1.tm_mon+1 < time2.tm_mon+1)
                printf("text1 is early\n");
        else
	{
          if(time1.tm_mday > time2.tm_mday)
		printf("text2 is early\n");
          else  if(time1.tm_mday < time2.tm_mday)
		printf("text1 is early\n");
          else
		printf("same date\n");
        }
}
