### ISSUE TITLE
파일 사이즈 크기 비교 코드 작성하겠습니다.

### ISSUE THREAD

**Issue by duswl9801** [junegives/Assignment2#4]

**Comment by duswl9801** [comment]
사이즈 크기 비교 코드입니다. 수정사항있으면 말해주세요!

if ( state1.st_size > state2.st_size )
   printf("state1 is bigger");
else if ( state1.st_size = state2.st_size )
   printf("sizes are equal");
else if ( state1.st_size < state2.st_size )
   printf("state2 is bigger")

**Comment by ChoiJuEon** [comment]
state1 을 전부 stat1으로 바꾸셔야합니다.
state2 또한 전부 stat2로 바꿔야하죠.

**Comment by duswl9801** [comment]
stat1,stat2으로 모두 바꿔 소스코드 수정하였습니다. 
if ( stat1.st_size > stat2.st_size )
 printf("stat1 is bigger");
 else if ( stat1.st_size = stat2.st_size )
 printf("sizes are equal");
 else if ( stat1.st_size < stat2.st_size )
 printf("stat2 is bigger")

**Comment by duswl9801** [comment]
printf안의 내용을 stat1,stat2대신에 text1,text2로 바꾸고 마지막에 \n넣어 소스 코드 완성하였습니다.
또한 중간 else if 안에 ==으로 고쳤습니다.
if ( stat1.st_size > stat2.st_size )
 printf("text1 is bigger\n");
 else if ( stat1.st_size == stat2.st_size )
 printf("sizes are equal\n");
 else if ( stat1.st_size < stat2.st_size )
 printf("text2 is bigger\n")
