### ISSUE TITLE
파일 블락 수 비교 코드 작성

### ISSUE THREAD

**Issue by junegives** [junegives/Assignment2#5]

**Comment by ChoiJuEon** [comment]
state1 >> stat1
state2 >> stat2

**Comment by junegives** [comment]
확인!!
수정하겠습니다.

**Comment by ChoiJuEon** [comment]
또한 stat1.st_block >>  stat.st_blocks로 고쳐야 합니다.

**Comment by junegives** [comment]
넵

**Comment by junegives** [comment]
오탈자 해결하였습니다.

printf("blocks number: ");
	if ( stat1.st_blocks > stat2.st_blocks )
		printf("text1 is bigger\n");
	else if ( stat1.st_blocks == stat2.st_blocks )
		printf("number of blocks are equal\n");
	else if ( stat1.st_blocks < stat2.st_blocks )
		printf("text2 is bigger\n");
