### ISSUE TITLE
충돌발생

### ISSUE THREAD

**Issue by duswl9801** [junegives/Assignment2#8]
error: Your local changes to the following files would be overwritten by merge:
	main.c
Please, commit your changes or stash them before you can merge.
Aborting
이런 메세지와 함께 충돌발생 오류가 떴습니다.

**Comment by junegives** [comment]
git stash 입력하면 됩니다

**Comment by duswl9801** [comment]
넵 git stash 하고 git pull해서 해결하였습니다. 감사합니다~
